//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Logic.BankRepublic {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wservicewsdlBinding", Namespace="urn:wservicewsdl")]
    public partial class wservicewsdl : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_key_base_64OperationCompleted;
        
        private System.Threading.SendOrPostCallback prueba_conexionOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificar_archivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback borrar_archivoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wservicewsdl() {
            this.Url = global::Logic.Properties.Settings.Default.Logic_BankRepublic_wservicewsdl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_key_base_64CompletedEventHandler get_key_base_64Completed;
        
        /// <remarks/>
        public event prueba_conexionCompletedEventHandler prueba_conexionCompleted;
        
        /// <remarks/>
        public event verificar_archivoCompletedEventHandler verificar_archivoCompleted;
        
        /// <remarks/>
        public event borrar_archivoCompletedEventHandler borrar_archivoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://bankrepublic.fundacionunipanamericana.com/webService/index.php/get_key_ba" +
            "se_64", RequestNamespace="../WebService/", ResponseNamespace="../WebService/")]
        public void get_key_base_64(ref string nombre) {
            object[] results = this.Invoke("get_key_base_64", new object[] {
                        nombre});
            nombre = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_key_base_64Async(string nombre) {
            this.get_key_base_64Async(nombre, null);
        }
        
        /// <remarks/>
        public void get_key_base_64Async(string nombre, object userState) {
            if ((this.get_key_base_64OperationCompleted == null)) {
                this.get_key_base_64OperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_key_base_64OperationCompleted);
            }
            this.InvokeAsync("get_key_base_64", new object[] {
                        nombre}, this.get_key_base_64OperationCompleted, userState);
        }
        
        private void Onget_key_base_64OperationCompleted(object arg) {
            if ((this.get_key_base_64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_key_base_64Completed(this, new get_key_base_64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://bankrepublic.fundacionunipanamericana.com/webService/index.php/prueba_con" +
            "exion", RequestNamespace="../WebService/", ResponseNamespace="../WebService/")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public string prueba_conexion(string request) {
            object[] results = this.Invoke("prueba_conexion", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void prueba_conexionAsync(string request) {
            this.prueba_conexionAsync(request, null);
        }
        
        /// <remarks/>
        public void prueba_conexionAsync(string request, object userState) {
            if ((this.prueba_conexionOperationCompleted == null)) {
                this.prueba_conexionOperationCompleted = new System.Threading.SendOrPostCallback(this.Onprueba_conexionOperationCompleted);
            }
            this.InvokeAsync("prueba_conexion", new object[] {
                        request}, this.prueba_conexionOperationCompleted, userState);
        }
        
        private void Onprueba_conexionOperationCompleted(object arg) {
            if ((this.prueba_conexionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.prueba_conexionCompleted(this, new prueba_conexionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://bankrepublic.fundacionunipanamericana.com/webService/index.php/verificar_" +
            "archivo", RequestNamespace="../WebService/", ResponseNamespace="../WebService/")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public string verificar_archivo(string request) {
            object[] results = this.Invoke("verificar_archivo", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verificar_archivoAsync(string request) {
            this.verificar_archivoAsync(request, null);
        }
        
        /// <remarks/>
        public void verificar_archivoAsync(string request, object userState) {
            if ((this.verificar_archivoOperationCompleted == null)) {
                this.verificar_archivoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onverificar_archivoOperationCompleted);
            }
            this.InvokeAsync("verificar_archivo", new object[] {
                        request}, this.verificar_archivoOperationCompleted, userState);
        }
        
        private void Onverificar_archivoOperationCompleted(object arg) {
            if ((this.verificar_archivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificar_archivoCompleted(this, new verificar_archivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://bankrepublic.fundacionunipanamericana.com/webService/index.php/borrar_arc" +
            "hivo", RequestNamespace="../WebService/", ResponseNamespace="../WebService/")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public string borrar_archivo(string request) {
            object[] results = this.Invoke("borrar_archivo", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void borrar_archivoAsync(string request) {
            this.borrar_archivoAsync(request, null);
        }
        
        /// <remarks/>
        public void borrar_archivoAsync(string request, object userState) {
            if ((this.borrar_archivoOperationCompleted == null)) {
                this.borrar_archivoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onborrar_archivoOperationCompleted);
            }
            this.InvokeAsync("borrar_archivo", new object[] {
                        request}, this.borrar_archivoOperationCompleted, userState);
        }
        
        private void Onborrar_archivoOperationCompleted(object arg) {
            if ((this.borrar_archivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.borrar_archivoCompleted(this, new borrar_archivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_key_base_64CompletedEventHandler(object sender, get_key_base_64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_key_base_64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_key_base_64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string nombre {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void prueba_conexionCompletedEventHandler(object sender, prueba_conexionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class prueba_conexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal prueba_conexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void verificar_archivoCompletedEventHandler(object sender, verificar_archivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificar_archivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificar_archivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void borrar_archivoCompletedEventHandler(object sender, borrar_archivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class borrar_archivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal borrar_archivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591