//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public string entity_id { get; set; }
        public string entity_name { get; set; }
        public string entity_description { get; set; }
        public string entity_publicKey { get; set; }
        public string entity_privateKey { get; set; }
    }
}
